### ISSUE TITLE
Escaping to literal `{{` and `}}`

### ISSUE THREAD

**Issue by explosion-mental** [SergioRibera/srtemplate#2]
**Is your feature request related to a problem? Please describe.**
It is, not sure how common that is, but is nice to have a way of escaping to produce literals.

**Describe the solution you'd like**
I think how [`far`](https://crates.io/crates/far) does it it's reasonable:
> Template authors can write {{{{}} or {{}}}} to get a literal {{ or }} respectively.

**Describe alternatives you've considered**
X

**Additional context**
X

**Comment by SergioRibera** [comment]
Uuuu this is interesting, I didn't think someone would need this, but in this case I think the most readable would be something like `\\{{\\}}` allow escape characters to exist

**Comment by explosion-mental** [comment]
Sure, personally I only needed escaping when the delimiters where `{` and `}` (conflicts with shell variables). Maybe just being able to change delimiters and being very strict would be a good option as well, what [go does it](https://groups.google.com/g/golang-nuts/c/cSHk1pkbasw).

**Comment by SergioRibera** [comment]
@explosion-mental Ooooo right, you are right, I had not taken into account that case, in theory it does support the {} uniques, but I will see how to make the delimiters customizable, I really like the idea

**Comment by SergioRibera** [comment]
Fixed on [v0.3.0](https://github.com/SergioRibera/srtemplate/releases/tag/v0.3.0) - [crates](https://crates.io/crates/srtemplate)
